name: Terraform Destroy
on:
 workflow_dispatch:
    inputs:
      environment:
        description: Environment to destroy
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
 terraform_destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    # Use OIDC to connect to AWS
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ${{ vars.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.6
          terraform_wrapper: false
      
      - name: Terraform Init
        id: init
        run: terraform init -reconfigure

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Validate
        id: validate
        run: terraform validate
        
      - name: Terraform Destroy
        id: destroy
        run: |
            terraform destroy \
            -var 'ecr_repo_name=test' \
            -auto-approve
